init:
  - "SET PATH=C:\\Python37\\Scripts;%PATH%"
  - "SET PYTEST_ADDOPTS=-vv"
  - "ECHO PATH=%PATH%"

build: off

environment:
  matrix:
    - TOXENV: "isort-check"
    - TOXENV: "lint"
    - TOXENV: "mypy"
    - TOXENV: "py35-coverage"
    - TOXENV: "py36-coverage"
    - TOXENV: "py37-coverage"

install:
  - pip install tox

test_script:
  - tox

on_success:
  # Add tox environment to PATH.
  - "SET PATH=%CD%\\.tox\\%TOXENV%\\scripts;%PATH%"
  - IF NOT "x%TOXENV:-coverage=%"=="x%TOXENV%" (
      pip install codecov &&
      coverage xml &&
      coverage report -m &&
      codecov --required -X gcov pycov search -f coverage.xml -n %TOXENV%-windows
    )
