package com.ljq.model;

/**
 * TZhuhu generated by MyEclipse Persistence Tools
 */

public class Household implements java.io.Serializable
{

	private static final long serialVersionUID = 1L;

	private String id;
	private String name;
	private String sex;
	private String age;
	private String telephone;
	private String address;
	private String password;
	private String regdate;
	private String remarks;

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getAge() {
		return age;
	}

	public void setAge(String age) {
		this.age = age;
	}

	public String getTelephone() {
		return telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getRegdate() {
		return regdate;
	}

	public void setRegdate(String regdate) {
		this.regdate = regdate;
	}

	public String getRemarks() {
		return remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	@Override
	public String toString() {
		return " [HOUSEHOLD id=" + id + ", name=" + name + ", sex=" + sex + ", age=" + age + ", telephone=" + telephone 
				+ ", address=" + address + ", password=" + password + ", regdate=" + regdate + ", remarks=" + remarks + "]  ";
	}
}